# Generated by Django 3.1.4 on 2020-12-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BitrateCalculator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bitrate",
            name="bitrate",
            field=models.CharField(default="--", max_length=2000),
        ),
        migrations.AddField(
            model_name="bitrate",
            name="episode",
            field=models.CharField(default="-", max_length=20),
        ),
        migrations.AddField(
            model_name="bitrate",
            name="time",
            field=models.CharField(default="-", max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="bitrate",
            name="size",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
