# Generated by Django 3.1.4 on 2020-12-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BitrateCalculator", "0002_auto_20201206_2347"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bitrate",
            name="bitrate",
            field=models.IntegerField(default="--", max_length=2000),
        ),
        migrations.AlterField(
            model_name="bitrate",
            name="episode",
            field=models.IntegerField(default="-"),
        ),
    ]
