# Generated by Django 3.2.4 on 2021-06-19 02:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundcore', '0009_alter_librarygenerator_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarygenerator',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 19, 8, 4, 49, 375477)),
            preserve_default=False,
        ),
    ]
