# Generated by Django 3.2.4 on 2021-06-19 02:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundcore', '0010_librarygenerator_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarygenerator',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 19, 8, 6, 2, 938971)),
        ),
    ]
