# Generated by Django 3.2.4 on 2021-06-19 02:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundcore', '0011_alter_librarygenerator_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarygenerator',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 19, 8, 13, 38, 151812)),
        ),
        migrations.AlterField(
            model_name='librarygenerator',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
