# Generated by Django 3.2.4 on 2021-06-19 02:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundcore', '0012_auto_20210619_0813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='librarygenerator',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='librarygenerator',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 19, 8, 36, 33, 638491)),
        ),
    ]
