# Generated by Django 3.2 on 2021-05-02 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="models",
        ),
    ]
