# Generated by Django 3.1.6 on 2021-02-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_rest', '0003_auto_20210215_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundcoremodel',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='soundcoremodel',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
