# Generated by Django 3.1 on 2020-08-09 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=50)),
                ('card_description', models.TextField(default=' ')),
                ('body_contect', models.TextField(default=' ')),
                ('date', models.DateTimeField()),
                ('pic', models.ImageField(upload_to='')),
                ('writer', models.CharField(default=' ', max_length=20)),
            ],
        ),
    ]
