# Generated by Django 3.1 on 2020-08-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_auto_20200826_0049"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="date",
            field=models.IntegerField(default="0"),
        ),
    ]
