# Generated by Django 3.1 on 2020-08-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0007_auto_20200826_1425"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="date",
            field=models.CharField(default="0", max_length=9),
        ),
    ]
