# Generated by Django 3.1 on 2020-08-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0008_auto_20200826_1907"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="time",
            field=models.CharField(default="00:00", max_length=5),
        ),
    ]
