# Generated by Django 3.2.4 on 2021-06-15 02:55

from django.db import migrations, models
import upload.helpers


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0016_rename_name_musiclist_song_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="musiclist",
            name="song_file",
            field=models.FileField(upload_to=upload.helpers.RandomFileName("songs")),
        ),
    ]
