# Generated by Django 3.2.4 on 2021-06-15 02:59

from django.db import migrations, models
import upload.helpers


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0018_rename_release_date_musiclist_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="musiclist",
            name="album_art",
            field=models.FileField(
                upload_to=upload.helpers.RandomFileName("album_art")
            ),
        ),
    ]
