# Generated by Django 3.2.4 on 2021-06-15 05:36

from django.db import migrations, models
import upload.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0022_alter_musiclist_album_art'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musiclist',
            name='album_art',
            field=models.FileField(upload_to=upload.helpers.RandomFileName('album_arts/')),
        ),
        migrations.AlterField(
            model_name='musiclist',
            name='song_file',
            field=models.FileField(upload_to=upload.helpers.RandomFileName('songs/')),
        ),
    ]
