# Generated by Django 3.1 on 2020-08-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="main_start",
            name="about",
            field=models.TextField(default="-"),
        ),
    ]
