# Generated by Django 3.1 on 2020-08-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_main_start_about"),
    ]

    operations = [
        migrations.AlterField(
            model_name="main_start",
            name="about",
            field=models.TextField(),
        ),
    ]
