# Generated by Django 3.1 on 2020-08-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_auto_20200809_0025"),
    ]

    operations = [
        migrations.AddField(
            model_name="main_start",
            name="twitter",
            field=models.TextField(default="-1"),
        ),
    ]
