# Generated by Django 3.1 on 2020-08-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200809_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_start',
            name='number',
            field=models.IntegerField(default='1'),
        ),
    ]
