# Generated by Django 3.1 on 2020-08-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_main_start_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="main_start",
            name="number",
            field=models.IntegerField(),
        ),
    ]
