# Generated by Django 3.1 on 2020-08-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_auto_20200809_0040"),
    ]

    operations = [
        migrations.AddField(
            model_name="main_start",
            name="site_name",
            field=models.TextField(default="-"),
        ),
    ]
