# Generated by Django 3.1 on 2020-08-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_main_start_site_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="main_start",
            name="site_name",
            field=models.TextField(),
        ),
    ]
