# Generated by Django 3.1 on 2020-08-09 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_auto_20200809_0849"),
    ]

    operations = [
        migrations.AlterField(
            model_name="main_start",
            name="facebook",
            field=models.CharField(default=" ", max_length=50),
        ),
        migrations.AlterField(
            model_name="main_start",
            name="github",
            field=models.CharField(default=" ", max_length=50),
        ),
        migrations.AlterField(
            model_name="main_start",
            name="link",
            field=models.CharField(default=" ", max_length=50),
        ),
        migrations.AlterField(
            model_name="main_start",
            name="site_creator",
            field=models.CharField(default=" ", max_length=15),
        ),
        migrations.AlterField(
            model_name="main_start",
            name="twitter",
            field=models.CharField(default=" ", max_length=50),
        ),
        migrations.AlterField(
            model_name="main_start",
            name="youtube",
            field=models.CharField(default=" ", max_length=50),
        ),
    ]
