# Generated by Django 3.1 on 2020-08-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200809_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_start',
            name='facebook',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='main_start',
            name='github',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='main_start',
            name='youtube',
            field=models.TextField(),
        ),
    ]
