# Generated by Django 3.1 on 2020-08-09 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_main_start_copyright'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='main_start',
            new_name='site_info',
        ),
    ]
