# Generated by Django 3.1.6 on 2021-02-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music_rest", "0002_auto_20210215_1944"),
    ]

    operations = [
        migrations.AlterField(
            model_name="soundcoremodel",
            name="author",
            field=models.CharField(max_length=200),
        ),
    ]
