# Generated by Django 3.1.4 on 2020-12-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("YoutubeDownloader", "0003_youtube_short_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="youtube",
            name="short_url",
        ),
        migrations.AddField(
            model_name="youtube",
            name="time",
            field=models.CharField(default=None, max_length=100),
        ),
    ]
