# Generated by Django 3.1.4 on 2020-12-06 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("YoutubeDownloader", "0004_auto_20201206_1103"),
    ]

    operations = [
        migrations.RenameField(
            model_name="youtube",
            old_name="file",
            new_name="file_location",
        ),
    ]
