# Generated by Django 3.1.4 on 2020-12-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YoutubeDownloader', '0005_auto_20201206_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube',
            name='secret',
            field=models.BinaryField(default=b'0'),
        ),
    ]
